# Generated by Django 6.0 on 2026-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='accommodation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='travel_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
