# Generated by Django 6.0 on 2026-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trip_accommodation_trip_travel_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='itinerary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='packing_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
